// chat-app/src/components/SettingsModal.tsx
import React, { useState } from 'react';
import { CloseIcon, SettingsIcon, DataManagementIcon } from './icons';

// 定义 Props 类型
interface SettingsModalProps {
    isOpen: boolean;
    onClose: () => void;
}

// 定义激活标签页的类型，以增强类型安全
type ActiveTab = 'general' | 'data';

/**
 * @description
 * 设置模态框组件。
 */
export const SettingsModal = ({ isOpen, onClose }: SettingsModalProps) => {
    // 内部状态，用于管理当前激活的标签页，并明确其类型
    const [activeTab, setActiveTab] = useState<ActiveTab>('general');

    if (!isOpen) {
        return null;
    }

    // ... 其余渲染逻辑与之前相同，但现在使用 TSX ...
    // 为简洁起见，此处不再重复，其内部结构不变。
    // 您只需将之前的 SettingsModal.jsx 内容复制过来，并确保文件名是 .tsx 即可。
    // React 会自动处理 JSX 到 TSX 的转换。
    // 关键是 props 和 state 的类型定义已经完成。
    const renderGeneralSettings = () => (
        <div className="flex-1 p-6 text-gray-800">
            <h2 className="text-lg font-semibold mb-6">通用设置</h2>
            <div className="space-y-4">
                <div className="flex items-center justify-between">
                    <label htmlFor="suggestions" className="text-sm text-gray-700">在聊天中显示跟进建议</label>
                    <div className="relative inline-block w-10 mr-2 align-middle select-none transition duration-200 ease-in">
                        <input type="checkbox" name="toggle" id="suggestions" defaultChecked className="toggle-checkbox absolute block w-6 h-6 rounded-full bg-white border-4 appearance-none cursor-pointer peer" />
                        <label htmlFor="suggestions" className="toggle-label block overflow-hidden h-6 rounded-full bg-gray-300 peer-checked:bg-blue-500 cursor-pointer"></label>
                    </div>
                </div>
                <div className="flex items-center justify-between">
                    <span className="text-sm text-gray-700">语言</span>
                    <button className="text-sm text-gray-500 hover:text-gray-800">自动检测 ▼</button>
                </div>
                <div className="flex items-center justify-between">
                    <span className="text-sm text-gray-700">已归档的聊天</span>
                    <button className="px-3 py-1 text-sm border rounded-md hover:bg-gray-100">管理</button>
                </div>
                <div className="flex items-center justify-between">
                    <span className="text-sm text-gray-700">归档所有聊天</span>
                    <button className="px-3 py-1 text-sm border rounded-md hover:bg-gray-100">全部归档</button>
                </div>
                <div className="flex items-center justify-between">
                    <span className="text-sm text-gray-700">删除所有聊天</span>
                    <button className="px-3 py-1 text-sm border rounded-md text-red-600 border-red-200 hover:bg-red-50">全部删除</button>
                </div>
                <div className="flex items-center justify-between">
                    <span className="text-sm text-gray-700">注销设备</span>
                    <button className="px-3 py-1 text-sm border rounded-md hover:bg-gray-100">注销</button>
                </div>
            </div>
        </div>
    );

    const renderDataSettings = () => (
        <div className="flex-1 p-6 text-gray-800">
            <h2 className="text-lg font-semibold mb-6">数据管理</h2>
            <div className="space-y-4">
                <div className="flex items-center justify-between">
                    <span className="text-sm text-gray-700">为所有用户改进模型</span>
                    <button className="text-sm text-blue-600 hover:underline">开 </button>
                </div>
                <div className="flex items-center justify-between">
                    <span className="text-sm text-gray-700">共享链接</span>
                    <button className="px-3 py-1 text-sm border rounded-md hover:bg-gray-100">管理</button>
                </div>
                <div className="flex items-center justify-between">
                    <span className="text-sm text-gray-700">导出数据</span>
                    <button className="px-3 py-1 text-sm border rounded-md hover:bg-gray-100">导出</button>
                </div>
                <div className="flex items-center justify-between">
                    <span className="text-sm text-gray-700">删除帐户</span>
                    <button className="px-3 py-1 text-sm border rounded-md text-red-600 border-red-200 hover:bg-red-50">删除</button>
                </div>
            </div>
        </div>
    );

    return (
        <div
            className="fixed inset-0 z-50 flex items-center justify-center bg-black bg-opacity-40 backdrop-blur-sm"
            onClick={onClose}
        >
            <div
                className="relative bg-white w-full max-w-3xl rounded-lg shadow-xl flex overflow-hidden"
                onClick={(e) => e.stopPropagation()}
            >
                <button onClick={onClose} className="absolute top-4 right-4 text-gray-400 hover:text-gray-600">
                    <CloseIcon className="w-5 h-5" />
                </button>

                <div className="w-1/4 bg-gray-50 border-r border-gray-200 p-4 space-y-2">
                    <button
                        onClick={() => setActiveTab('general')}
                        className={`w-full text-left text-sm p-2 rounded-md flex items-center gap-3 ${activeTab === 'general' ? 'bg-gray-200 text-gray-800 font-semibold' : 'text-gray-600 hover:bg-gray-100'}`}
                    >
                        <SettingsIcon className="w-4 h-4 text-gray-500" />
                        通用设置
                    </button>
                    <button
                        onClick={() => setActiveTab('data')}
                        className={`w-full text-left text-sm p-2 rounded-md flex items-center gap-3 ${activeTab === 'data' ? 'bg-gray-200 text-gray-800 font-semibold' : 'text-gray-600 hover:bg-gray-100'}`}
                    >
                        <DataManagementIcon className="w-4 h-4 text-gray-500" />
                        数据管理
                    </button>
                </div>

                {activeTab === 'general' ? renderGeneralSettings() : renderDataSettings()}
            </div>
        </div>
    );
};

// chat-app/src/components/SettingsModal.vue
<template>
  <div class="modal-overlay" @click.self="emit('close')">
    <div class="modal-content">
      <button class="close-button" @click="emit('close')">
        <Icon name="close" />
      </button>
      <div class="modal-layout">
        <div class="modal-nav">
          <button
            :class="['nav-item', { active: activeTab === 'general' }]"
            @click="activeTab = 'general'"
          >
            <Icon name="settings" />
            <span>通用设置</span>
          </button>
          <button
            :class="['nav-item', { active: activeTab === 'data' }]"
            @click="activeTab = 'data'"
          >
            <Icon name="data_management" />
            <span>数据管理</span>
          </button>
        </div>
        <div class="modal-main">
          <!-- 通用设置面板 -->
          <div v-if="activeTab === 'general'" class="settings-panel">
            <div class="setting-item">
              <label>主题</label>
              <select class="settings-dropdown">
                <option>系统</option>
              </select>
            </div>
            <div class="separator"></div>
            <div class="setting-item">
              <label>在聊天中显示路标建议</label>
              <div class="switch-container">
                <input type="checkbox" id="suggestions-toggle" class="switch-input" checked />
                <label for="suggestions-toggle" class="switch-label"></label>
              </div>
            </div>
            <div class="separator"></div>
            <div class="setting-item">
              <label>语言</label>
              <select class="settings-dropdown">
                <option>自动检测</option>
              </select>
            </div>
            <div class="separator"></div>
            <div class="setting-item">
              <label>已归档的聊天</label>
              <button class="settings-button">管理</button>
            </div>
            <div class="separator"></div>
            <div class="setting-item">
              <label>归档所有聊天</label>
              <button class="settings-button">全部归档</button>
            </div>
            <div class="separator"></div>
            <div class="setting-item">
              <label>删除所有聊天</label>
              <button class="settings-button danger">全部删除</button>
            </div>
            <div class="separator"></div>
            <div class="setting-item">
              <label>注销设备</label>
              <button class="settings-button">注销</button>
            </div>
          </div>

          <!-- 数据管理面板 -->
          <div v-if="activeTab === 'data'" class="settings-panel">
            <div class="setting-item">
              <label>为所有用户改进模型</label>
              <a href="#" class="toggle-link">开 ></a>
            </div>
            <div class="separator"></div>
            <div class="setting-item">
              <label>共享链接</label>
              <button class="settings-button">管理</button>
            </div>
            <div class="separator"></div>
            <div class="setting-item">
              <label>导出数据</label>
              <button class="settings-button">导出</button>
            </div>
            <div class="separator"></div>
            <div class="setting-item">
              <label>删除帐户</label>
              <button class="settings-button danger">删除</button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import Icon from './AppIcon.vue'

const emit = defineEmits(['close'])
const activeTab = ref('general')
</script>

<style scoped>
.modal-overlay {
  position: fixed;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  background-color: var(--bg-overlay);
  display: flex;
  justify-content: center;
  align-items: center;
  z-index: 1000;
  backdrop-filter: blur(8px);
}

.modal-content {
  background-color: var(--modal-bg);
  border-radius: var(--border-radius-large);
  width: 800px;
  height: 600px;
  position: relative;
  overflow: hidden;
  box-shadow: 0 10px 30px rgba(0, 0, 0, 0.5);
}

.close-button {
  position: absolute;
  top: 16px;
  left: 16px;
  background: none;
  border: none;
  color: var(--text-secondary);
  cursor: pointer;
  padding: 8px;
  border-radius: 50%;
  display: flex;
  align-items: center;
  justify-content: center;
  z-index: 10;
  transition: background-color 0.2s, color 0.2s;
}
.close-button:hover {
  background-color: var(--bg-tertiary);
  color: var(--text-primary);
}
.close-button :deep(svg) {
  font-size: 20px;
}

.modal-layout {
  display: flex;
  height: 100%;
}

.modal-nav {
  width: 240px;
  background-color: var(--modal-nav-bg);
  padding: 60px 16px 16px;
  display: flex;
  flex-direction: column;
  gap: 4px;
}

.nav-item {
  display: flex;
  align-items: center;
  gap: 12px;
  padding: 12px;
  border-radius: 8px;
  background: none;
  border: none;
  color: var(--text-secondary);
  cursor: pointer;
  font-size: 1em;
  text-align: left;
  width: 100%;
}

.nav-item:hover {
  background-color: var(--bg-tertiary);
  color: var(--text-primary);
}

.nav-item.active {
  background-color: var(--button-primary-bg);
  color: var(--text-primary);
}

.nav-item :deep(svg) {
  font-size: 18px;
}

.modal-main {
  flex-grow: 1;
  padding: 24px 32px;
  overflow-y: auto;
}

.settings-panel {
  display: flex;
  flex-direction: column;
}

.setting-item {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 20px 0;
  font-size: 1em;
}

.setting-item label {
  color: var(--text-primary);
}

.separator {
  height: 1px;
  background-color: var(--border-color);
  width: 100%;
}

.settings-button {
  background-color: var(--button-secondary-bg);
  color: var(--text-primary);
  border: none;
  padding: 8px 16px;
  border-radius: 8px;
  cursor: pointer;
  font-size: 0.9em;
}
.settings-button:hover {
  filter: brightness(1.2);
}

.settings-button.danger {
  background-color: transparent;
  color: var(--text-danger);
  border: 1px solid var(--text-danger);
}
.settings-button.danger:hover {
  background-color: var(--text-danger);
  color: var(--button-danger-text);
}

.settings-dropdown {
  background-color: var(--button-secondary-bg);
  color: var(--text-primary);
  border: 1px solid var(--border-color);
  padding: 8px 12px;
  border-radius: 8px;
}

.toggle-link {
  color: var(--link-color);
  text-decoration: none;
  font-weight: 500;
}

.switch-container {
  position: relative;
  width: 44px;
  height: 24px;
}

.switch-input {
  opacity: 0;
  width: 0;
  height: 0;
}

.switch-label {
  position: absolute;
  cursor: pointer;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  background-color: var(--switch-bg-off);
  transition: 0.4s;
  border-radius: 34px;
}

.switch-label:before {
  position: absolute;
  content: '';
  height: 20px;
  width: 20px;
  left: 2px;
  bottom: 2px;
  background-color: white;
  transition: 0.4s;
  border-radius: 50%;
}

.switch-input:checked + .switch-label {
  background-color: var(--switch-bg-on);
}

.switch-input:checked + .switch-label:before {
  transform: translateX(20px);
}
</style>
